# Generated by Django 4.1.3 on 2022-11-10 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_alter_address_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='COD', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.FloatField(default=0)),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='website.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admn.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
