# Generated by Django 4.1.3 on 2022-11-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_historyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Received', 'Received'), ('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Received', max_length=100, null=True),
        ),
    ]
