# Generated by Django 4.1.3 on 2022-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_historyorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Order Placed', max_length=100, null=True),
        ),
    ]
