# Generated by Django 4.1.3 on 2022-11-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0001_initial'),
        ('website', '0009_alter_historyorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admn.product'),
        ),
    ]
