# Generated by Django 4.1.3 on 2022-11-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_historyorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyorder',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
