# Generated by Django 4.1.3 on 2022-11-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rename_updated_date_historyorder_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
