# Generated by Django 4.1.3 on 2022-11-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_historyorder_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyorder',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historyorder',
            name='outfordelivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historyorder',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historyorder',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
