# Generated by Django 4.1.3 on 2022-12-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0005_alter_myuser_phone_number'),
        ('website', '0018_historyorder_cancelled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admn.product'),
        ),
    ]
