# Generated by Django 4.1.3 on 2022-12-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_historyorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyorder',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='website.address'),
        ),
    ]
