# Generated by Django 4.1.3 on 2022-11-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_amnt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_amnt',
            field=models.FloatField(default=0.0),
        ),
    ]
