# Generated by Django 4.1.3 on 2022-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0004_product_category_offer_product_category_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
